const fs = require('fs');

/**
 * @namespace FileUtil
 *
 */
var FileUtil = {
    access: require('./access'),
    accessSync: require('./accessSync'),
    appendFile: require('./appendFile'),
    appendFileSync: require('./appendFileSync'),
    chmod: require('./chmod'),
    chmodSync: require('./chmodSync'),
    chown: require('./chown'),
    chownSync: require('./chownSync'),
    close: require('./close'),
    closeSync: require('./closeSync'),
    constants: require('./constants'),
    createReadStream: require('./createReadStream'),
    createReadStreamSync: require('./createReadStreamSync'),
    createWriteStream: require('./createWriteStream'),
    createWriteStreamSync: require('./createWriteStreamSync'),
    fchmod: require('./fchmod'),
    fchmodSync: require('./fchmodSync'),
    fchown: require('./fchown'),
    fchownSync: require('./fchownSync'),
    fdatasync: require('./fdatasync'),
    fdatasyncSync: require('./fdatasyncSync'),
    fstat: require('./fstat'),
    fstatSync: require('./fstatSync'),
    fsync: require('./fsync'),
    fsyncSync: require('./fsyncSync'),
    ftruncate: require('./ftruncate'),
    ftruncateSync: require('./ftruncateSync'),
    futimes: require('./futimes'),
    futimesSync: require('./futimesSync'),
    lchmod: require('./lchmod'),
    lchmodSync: require('./lchmodSync'),
    lchown: require('./lchown'),
    lchownSync: require('./lchownSync'),
    link: require('./link'),
    linkSync: require('./linkSync'),
    lstat: require('./lstat'),
    lstatSync: require('./lstatSync'),
    mkdir: require('./mkdir'),
    mkdirSync: require('./mkdirSync'),
    mkdtemp: require('./mkdtemp'),
    mkdtempSync: require('./mkdtempSync'),
    open: require('./open'),
    openSync: require('./openSync'),
    read: require('./read'),
    readdir: require('./readdir'),
    readdirSync: require('./readdirSync'),
    readFile: require('./readFile'),
    readFileSync: require('./readFileSync'),
    readlink: require('./readlink'),
    readlinkSync: require('./readlinkSync'),
    readSync: require('./readSync'),
    realpath: require('./realpath'),
    realpathSync: require('./realpathSync'),
    rename: require('./rename'),
    renameSync: require('./renameSync'),
    rmdir: require('./rmdir'),
    rmdirSync: require('./rmdirSync'),
    stat: require('./stat'),
    statSync: require('./statSync'),
    symlink: require('./symlink'),
    symlinkSync: require('./symlinkSync'),
    truncate: require('./truncate'),
    truncateSync: require('./truncateSync'),
    unlink: require('./unlink'),
    unlinkSync: require('./unlinkSync'),
    unwatchFile: require('./unwatchFile'),
    unwatchFileSync: require('./unwatchFileSync'),
    utimes: require('./utimes'),
    utimesSync: require('./utimesSync'),
    watch: require('./watch'),
    watchFile: require('./watchFile'),
    watchFileSync: require('./watchFileSync'),
    watchSync: require('./watchSync'),
    write: require('./write'),
    writeFile: require('./writeFile'),
    writeFileSync: require('./writeFileSync'),
    writeSync: require('./writeSync')
};

FileUtil.FSWatcher = fs.FSWatcher;
FileUtil.Stats = fs.Stats;

module.exports = FileUtil;
